---
- hosts: localhost
  remote_user: root
  connection: ssh
  gather_facts: no
  aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
  aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  roles:
    - vpc
    - ec2sg
    - ec2key
    - ec2instance
    - elb
    - rds
