--- # Testing how variables work in the vars sesction of a playbook
- hosts: '{{myhosts}}'
  remote_user: ansible
  become_user: root
  connection: ssh
  gather_facts: '{{gather}}'
  vars:
    myhosts: local
    gather: yes
    pkg: telnet
  tasks:
  - name: Install the indicated softwaer
    yum:
      name: '{{pkg}}'
      state: latest
